### PR TITLE
Merge in debug kit updates

### PR DESCRIPTION
**Pull request by npwalker**

### CODE REVIEW

**Comment by smcclellan** [comment]
@npwalker 198 commits? Maybe better to wait until the other PR gets merged, too. What's the value-add?

**Comment by npwalker** [comment]
This is the result of `git pull debugkit master --allow-unrelated-histories` since when I made this stack I didn't have the sense to start with a clone of the debug kit.

Then I replaced some of the custom roles with roles the debug kit now provides.

**Comment by smcclellan** [comment]
@npwalker Would a git submodule work for this, too? The repo would be in a separate directory, so maybe we couldn't link to that directory, but that seems easier for keeping [that repo](https://github.com/Sharpie/puppet-debugging-kit)'s history.

**Comment by npwalker** [comment]
I don't think it can be a sub module because the configuration directory is part of that repo and we need to modify files in it...

**Comment by npwalker** [comment]
@Sharpie thoughts on how to update the debug kit without bringing in all 200 commits?

**Comment by smcclellan** [comment]
https://github.com/puppetlabs/pe-razor-vagrant-stack/pull/17 is another option, using git submodule and copying over the changed bits of:
- Vagrantfile
- .gitignore
rsync_ignore

**Comment by npwalker** [comment]
If #17 works and @Sharpie says it's not a terrible idea then it seems like a reasonable solution.

**Comment by Sharpie** [comment]
I suppose you could try squashing it all down to one commit. Otherwise #17 seems fine. I don't predict any changes in the layout of the upstream repository and would actively avoid creating any.

**Comment by smcclellan** [comment]
Merged via https://github.com/puppetlabs/pe-razor-vagrant-stack/pull/17.

**Pull request closed without merging**
